### PR TITLE
Adds The Manager's Path by Camille Fournier

### PR DESCRIPTION
**Pull request by Raffo**
I'm not sure this is the kind of form or section for this entry, but I'm reading this book and I find it really inspiring. It could be perfect for a section about transitioning to management as it offer a bunch of examples and suggestions for managers at different levels.

### CODE REVIEW

**Comment by alexkops** [comment]
Hmm, maybe add a books section? Or mark it as a book somehow? I'd expect that all the links in this list would be free reads, but collecting good books would definitely be a good addition.

**Comment by Raffo** [comment]
The README says: 

> Please share/promote your favorite managing and leading resources/go-to's (books, articles, Twitter feeds, videos, etc.) by adding them to this list. 

So I would expect that books are welcome. We could make more explicit the difference between entries in the list by making the type of resource more explicit. This would probably make the experience easier for the reader as she will not need to jump on something "to buy" instead of something that is immediately available for free.

**Comment by alexkops** [comment]
There are free books as well ;) But I agree, maybe put a dollar sign or something behind a link to indicate that it's behind a paywall or is a book that needs to be purchased.

**Comment by LappleApple** [comment]
@Raffo Woo hoo, thanks! Was wondering when someone would add that. :) 

@alexkops Like where you're going with this idea; perhaps every page should separate out the "books."

**Pull request merged**
