### PR TITLE
Articles on interviewing and leadership

### PR DESCRIPTION
**Pull request by xdg**
The interviewing ones have been sitting around half finished since shortly after my last PR.  But I found some time this AM while Ms. 6 was in a class to finish them and add the VPE article you asked for on Twitter.

### CODE REVIEW

**Comment by LappleApple** [comment]
Thanks a lot! :)

**Comment by LappleApple** [comment]
Oh hey, if you could recap on the Contributing.md next time that would be great (alphabetization, capitalization style guidelines). :)

**Comment by xdg** [comment]
Sorry about that.  I'll double check it next time and make sure I'm up to date before submitting.  I would have cleaned it up myself but you've already done it.  Thank you.

On the CONTRIBUTING file itself -- I just read it and have the following comments/questions:

* You might clarify that you want title casing *regardless of the original article's case*.  Normally, I would leave an original author's title verbatim.
* I've noticed the attribution style changed at some point.  From `[title](link): by author` to `[title](link) - by author`.  If that's intentional, you might want to add that to the guidelines or even give a more complete template: `[title](link) - by author.  Takeaway(s): ...`
* You don't mention if takeaways can be in sub-bullets, need to be in complete sentences, etc.
* You don't mention if alphabetical order should ignore "The".  Your edit to my submissions suggest it should.  Are there other stop words that should be ignored for alphabetical ordering?
* I don't understand what you mean by "the body of your commit message should contain a link to the repository".  Could you please give an example?
* You say "the pull request and commit should have a useful title", but most of the commits in the repo already don't.  You might clarify if this is a "do as I say, not as I do" policy.  (E.g. "I know what I'm committing so my messages are brief, but when I review PRs/commits, it helps me to have a more expressive PR/commit title from you".)
* For a case like mine, with many articles to submit, you might want to mention if you want them as a single commit, or a commit per item (within a single pull request).  (Maybe that goes in an "advanced git users" section -- so you don't scare off people who are using GitHub for the first time. 😄 )

And thanks again for putting together this tremendous resource!

**Comment by LappleApple** [comment]
Thanks, I made some changes based on your helpful comments. The "one commit per item" was in there but now I've used bold to make concepts stand out more clearly.

**Pull request merged**
