### PR TITLE
Add my latest article on Tech-Lead-Talks blog.

### PR DESCRIPTION
**Pull request by elbrujohalcon**
As requested by @LappleApple on Slack.

### CODE REVIEW

**Comment by LappleApple** [comment]
Thanks, @elbrujohalcon. Going forward, would be great if you could follow the guidelines:

https://github.com/LappleApple/awesome-leading-and-managing/blob/master/CONTRIBUTING.md

👍

**Comment by elbrujohalcon** [comment]
I read those before submitting the PR, what did I do wrong? 🙈

**Comment by LappleApple** [comment]
Alphabetical order. :) But it's OK! I fixed it already (it was almost in the right place, just one item up and BOOM)

**Comment by elbrujohalcon** [comment]
OMG! You're totally right! Thank you 😊

**Pull request merged**
